### Write a function so that the columns of the output matrix are powers of the input vector.

### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [12]:
def mat_power(in_vec, n, increasing = False):
  if increasing:
    Output_m = np.matrix([x**i for x in in_vec for i in range(n)]).reshape(in_vec.size, n)
  else:
    Output_m = np.matrix([x**(n-i-1) for x in in_vec for i in range(n)]).reshape(in_vec.size, n)
  return Output_m

In [18]:
in_vec = np.array([2, 3, 5, 4])
n = 3

In [19]:
Output_mat = mat_power(in_vec, n, True)
Output_mat

matrix([[ 1,  2,  4],
        [ 1,  3,  9],
        [ 1,  5, 25],
        [ 1,  4, 16]])

In [20]:
Output_mat = mat_power(in_vec, n, False)
Output_mat

matrix([[ 4,  2,  1],
        [ 9,  3,  1],
        [25,  5,  1],
        [16,  4,  1]])

Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of

the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.


# Question: Write a function to find moving average in an array over a window: 
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [38]:
def Mov_avgFun(in_list, k):
  count = 1
  mov_avg = np.convolve(in_list, np.ones(k), 'valid') / k
  for i in mov_avg:
    print("y{0} = {1:.2f} ".format(count, i))
    count += 1

In [40]:
value = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
Mov_avgFun(value, k)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
y1 = 5.00 
y2 = 4.67 
y3 = 5.67 
y4 = 6.67 
y5 = 9.67 
y6 = 28.67 
y7 = 49.33 
y8 = 72.67 
y9 = 84.00 
y10 = 93.33 
y11 = 116.33 


In [37]:
np.ones(k)

array([1., 1., 1.])